# Usar uma imagem base do Python
FROM python:3.9-slim

# Definir o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar os arquivos do projeto
COPY . .

# Instalar dependências
RUN pip install --no-cache-dir -r requirements.txt

# Expor a porta 8080 (usada pelo Cloud Run)
EXPOSE 8080

# Comando para rodar o aplicativo Flask
CMD ["gunicorn", "-b", "0.0.0.0:8080", "website:create_app()"]
